name: heplify-server ghcr build + push

on:
  push:
    branches: ['homer7', 'master']
    paths-ignore: ['**/*.md']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Clone homer-app
        uses: actions/checkout@v3
        with:
          repository: spacetourist/heplify-server
          path: 'heplify-server'
      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3.0.0
        with:
          context: ./heplify-server
          file: ./heplify-server/docker/Dockerfile
          push: true
          tags: |
             ghcr.io/spacetourist/heplify-server:latest
